server:
  port: 8080
  servlet:
    context-path: /authentication
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/authentication"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mailServer:
  host: smtp.gmail.com
  port: 587
  email: gamekmoba@gmail.com
  password: ybiu zfrx svit ocim
  protocol: smtp
  isSSL: false
